# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run all tests"
  lane :tests do
    test(destination: "platform=iOS Simulator,name=iPhone 11", swift_version: "5.2")
  end

  desc "Run all tests within CI"
  lane :tests_ci do
    test(destination: ENV["DESTINATION"], swift_version: ENV["SWIFT_VERSION"])
  end

  lane :test do |options|
    scan(
      scheme: "Crystal", 
      clean: true, 
      xcargs: "SWIFT_VERSION=#{options[:swift_version]}",
      destination: options[:destination]
    )
  end
end
